name: Feature_branch_push

on:
  push:
   # branches:
    #  - 'feature/**'

jobs:
  terraform:
    runs-on: GitHubRunner
    name: Terraform Job
    steps:
      - name: test task checking
        run: echo "just checking the task"

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: terraform_1.13.1
                
        
    
